[package]
name = "_pattern"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "example"
path = "src/main.rs"


[lib]
name = "lib_example"
path = "src/lib.rs"

[dependencies]
#mockall = "0.11.4"
#rstest = "0.17.0"
#thiserror = "1.0.40"
